name: movies_dribbble
description: Flutter UI Study Group
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-125.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  flutter_staggered_grid_view: ^0.3.2
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  provider: ^4.3.2+3
  widgets_visibility_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
